**Series**

In [63]:
import pandas as pd

In [4]:
data = [100, 102, 104]

series = pd.Series(data)  # Series constructor to make a series of data
print(series)

0    100
1    102
2    104
dtype: int64

In [5]:
data = ["A", "B", "C", "D"]
series = pd.Series(data)
print(series)

0    A
1    B
2    C
3    D
dtype: str

In [6]:
data = [100.1, 102.2, 104.3]
series = pd.Series(data, index = ["Num-1:", "Num-2:", "Num-3:"])  # customized indexing (by default 0,1,2....)
print(series)

Num-1:    100.1
Num-2:    102.2
Num-3:    104.3
dtype: float64

In [7]:
series = pd.Series(data, index = ["a","b","c"])
print(f"{series.loc["a"]}, {series.loc["b"]}, {series.loc["c"]}") # loc -> location by level
# print(series["d"])  # Key Error

100.1, 102.2, 104.3

In [8]:
# iloc -> integer location
print(series.iloc[0])
print(series.iloc[1])  # iloc only takes integer
print(series.iloc[2])

100.1
102.2
104.3

In [22]:
# Dictionary as series
ct_marks = {
    "Alice" : 12,
    "Bob" : 16,
    "Badhon" : 18,
    "Sakib" : 20,
    "Messi" : 6
    }
_marks = pd.Series(ct_marks)
_marks

Alice     12
Bob       16
Badhon    18
Sakib     20
Messi      6
dtype: int64

In [23]:
# Conditional Accessing
print(_marks[_marks >= 15])

Bob       16
Badhon    18
Sakib     20
dtype: int64

In [24]:
# Modification
_marks["Messi"] += 9
_marks["Roney"] = 11
_marks[_marks %2 == 1]

Messi    15
Roney    11
dtype: int64

In [16]:
_marks

Alice     12
Bob       16
Badhon    18
Sakib     20
Messi     15
Roney     11
dtype: int64

**Data Frame**

In [13]:
data = {
    "Name": ["Badhon", "Alice", "Bob"],
    "Age": [20, 21, 22]
}
df = pd.DataFrame(data)

df

     Name  Age
0  Badhon   20
1   Alice   21
2     Bob   22

In [4]:
df.shape

(3, 2)

In [15]:
techLeaders = {
    "Name" : ["Bill", "Bezos", "Musk"],  # Name, Age are separate columns
    "Age" : [67, 45, 52]
}

df = pd.DataFrame(techLeaders, index = ["Leader 1", "Leader 2", "Leader 3"])
df

           Name  Age
Leader 1   Bill   67
Leader 2  Bezos   45
Leader 3   Musk   52

In [26]:
# Add new column
df["Company"] = ["Microsoft", "Amazon", "Tesla"]
df

           Name  Age    Company
Leader 1   Bill   67  Microsoft
Leader 2  Bezos   45     Amazon
Leader 3   Musk   52      Tesla

In [ ]:
# Add new rows
new_row = pd.DataFrame([{"Name" : "Altman", "Age": 40, "Company" : "OpenAI"},{"Name" : "Jack Ma", "Age": 58, "Company" : "Alibaba"}], index = ["Leader 4", "Leader 5"])
df = pd.concat([df, new_row])
print(df)

             Name  Age    Company
Leader 1     Bill   67  Microsoft
Leader 2    Bezos   45     Amazon
Leader 3     Musk   52      Tesla
Leader 4   Altman   40     OpenAI
Leader 4   Altman   40     OpenAI
Leader 5  Jack Ma   58    Alibaba

**Import**

In [68]:
# Data Set loading ....
data_url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
titanic_df = pd.read_csv(data_url)   # csv file

In [ ]:
# print(titanic_df.to_string())  -> to print every row without getting truncated
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [33]:
titanic_df.head() # first 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [67]:
titanic_df.tail() # last 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
Ticket,,,,,,,,,,,
211536,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,13.00,NaN,S
112053,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,30.00,B42,S
W./C. 6607,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.45,NaN,S
111369,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,30.00,C148,C
370376,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,7.75,NaN,Q

In [35]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [36]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
titanic_df.isnull().sum()  # which columns have how many missing values

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [47]:
# Loading JSON file ....
_json_df = pd.read_json(r"E:\Pandas\Demo.json")
_json_df
# print(_json_df.to_string())

     name  age department  cgpa
0  Symond   20        CSE  3.85
1   Alice   21        EEE  3.92
2     Bob   22         ME  3.70

In [49]:
_json_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        3 non-null      str
 1   age         3 non-null      int64
 2   department  3 non-null      str
 3   cgpa        3 non-null      float64
dtypes: float64(1), int64(1), str(2)
memory usage: 228.0 bytes

In [ ]:
_json_df.describe()  # only show for numerical data's

        age      cgpa
count   3.0  3.000000
mean   21.0  3.823333
std     1.0  0.112398
min    20.0  3.700000
25%    20.5  3.775000
50%    21.0  3.850000
75%    21.5  3.885000
max    22.0  3.920000

**Selection**

In [ ]:
titanic_df["Name"]  # Actually a series
# print(titanic_df["Name"].to_string()) -> To see full column

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [65]:
# Accessing Multiple Columns
titanic_df[["Name", "Embarked", "Survived"]]

,Name,Embarked,Survived
Ticket,,,
A/5 21171,"Braund, Mr. Owen Harris",S,0
PC 17599,"Cumings, Mrs. John Bradley (Florence Briggs Th...",C,1
STON/O2. 3101282,"Heikkinen, Miss. Laina",S,1
113803,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",S,1
373450,"Allen, Mr. William Henry",S,0
...,...,...,...
211536,"Montvila, Rev. Juozas",S,0
112053,"Graham, Miss. Margaret Edith",S,1
W./C. 6607,"Johnston, Miss. Catherine Helen ""Carrie""",S,0
111369,"Behr, Mr. Karl Howell",C,1
370376,"Dooley, Mr. Patrick",Q,0

In [66]:
# Access Row(s)
titanic_df.loc[0]

KeyError: 0

In [70]:
# We can also use custom indexing and access using loc
_titanic_df = pd.read_csv(data_url, index_col="Ticket") 
_titanic_df   # Data Frame indexed with Ticket

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
Ticket,,,,,,,,,,,
A/5 21171,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,NaN,S
PC 17599,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C85,C
STON/O2. 3101282,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,NaN,S
113803,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,C123,S
373450,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
211536,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,13.0000,NaN,S
112053,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,30.0000,B42,S
W./C. 6607,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.4500,NaN,S
111369,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,30.0000,C148,C
370376,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,7.7500,NaN,Q

In [ ]:
_titanic_df.index.is_unique  # That's why the output for the cell below is 4 rows

False

In [71]:
_titanic_df.loc[["W./C. 6607", "113803"]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
Ticket,,,,,,,,,,,
W./C. 6607,784,0,3,"Johnston, Mr. Andrew G",male,NaN,1,2,23.45,NaN,S
W./C. 6607,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.45,NaN,S
113803,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.10,C123,S
113803,138,0,1,"Futrelle, Mr. Jacques Heath",male,37.0,1,0,53.10,C123,S

In [72]:
# Suppose we need three columnn instead all
titanic_df.loc[2, ["Name", "Age", "Sex"]]

Name    Heikkinen, Miss. Laina
Age                       26.0
Sex                     female
Name: 2, dtype: object

In [77]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [79]:
# From row indexed 1 to 5 and column Pclass to Age
titanic_df.loc[1:5 , "Pclass" : "Age"]

   Pclass                                               Name     Sex   Age
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2       3                             Heikkinen, Miss. Laina  female  26.0
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4       3                           Allen, Mr. William Henry    male  35.0
5       3                                   Moran, Mr. James    male   NaN

In [ ]:
# Using iloc -> From row 1 to 10 skipping 2 steps and columns 0 to 5
titanic_df.iloc[1:10:2, 0:5]  # same as slicing

,PassengerId,Survived,Pclass,Name,Sex
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female
5,6,0,3,"Moran, Mr. James",male
7,8,0,3,"Palsson, Master. Gosta Leonard",male
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female

In [84]:
# All rows and Name, Sex, Survived columns
titanic_df.iloc[:,[3,4,1]]

                                                  Name     Sex  Survived
0                              Braund, Mr. Owen Harris    male         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female         1
2                               Heikkinen, Miss. Laina  female         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female         1
4                             Allen, Mr. William Henry    male         0
..                                                 ...     ...       ...
886                              Montvila, Rev. Juozas    male         0
887                       Graham, Miss. Margaret Edith  female         1
888           Johnston, Miss. Catherine Helen "Carrie"  female         0
889                              Behr, Mr. Karl Howell    male         1
890                                Dooley, Mr. Patrick    male         0

[891 rows x 3 columns]

In [86]:
# Rows 20 to 30 & Columns starting to 4
titanic_df.iloc[20:31, :4]

,PassengerId,Survived,Pclass,Name
20,21,0,2,"Fynney, Mr. Joseph J"
21,22,1,2,"Beesley, Mr. Lawrence"
22,23,1,3,"McGowan, Miss. Anna ""Annie"""
23,24,1,1,"Sloper, Mr. William Thompson"
24,25,0,3,"Palsson, Miss. Torborg Danira"
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia..."
26,27,0,3,"Emir, Mr. Farred Chehab"
27,28,0,1,"Fortune, Mr. Charles Alexander"
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie"""
29,30,0,3,"Todoroff, Mr. Lalio"
30,31,0,1,"Uruchurtu, Don. Manuel E"

In [92]:
# Suppose, you wanna build a system that will take one passenger's ticket no 
# as input and print all his/her details
from IPython.display import display  
passenger = input("Enter Ticket No: ")
try :
    display(_titanic_df.loc[passenger])  # better display over normal print function
except KeyError :
    print(f"{passenger} not a valid ticket no.")

22712737 not a valid ticket no.

**Filtering**

In [94]:
# Let's see who survived
titanic_df[titanic_df["Survived"] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
len(titanic_df[titanic_df["Survived"] == 1])
# OR, titanic_df[titanic_df["Survived"] == 1].shape[0]

342

In [100]:
# Male and Survived
titanic_df[(titanic_df["Sex"]=="male") & (titanic_df["Survived"]==1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [102]:
# From Pclass 3, which females survived & Embarked from Quinston
titanic_df[(titanic_df["Pclass"]==3) & (titanic_df["Sex"]=="female") & (titanic_df["Survived"] == 1) & (titanic_df["Embarked"] == "Q")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
44,45,1,3,"Devaney, Miss. Margaret Delia",female,19.0,0,0,330958,7.8792,NaN,Q
47,48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q
82,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,NaN,Q
109,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
156,157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.0,0,0,35851,7.7333,NaN,Q
186,187,1,3,"O'Brien, Mrs. Thomas (Johanna ""Hannah"" Godfrey)",female,NaN,1,0,370365,15.5000,NaN,Q
198,199,1,3,"Madigan, Miss. Margaret ""Maggie""",female,NaN,0,0,370370,7.7500,NaN,Q
208,209,1,3,"Carr, Miss. Helen ""Ellen""",female,16.0,0,0,367231,7.7500,NaN,Q
241,242,1,3,"Murphy, Miss. Katherine ""Kate""",female,NaN,1,0,367230,15.5000,NaN,Q
274,275,1,3,"Healy, Miss. Hanora ""Nora""",female,NaN,0,0,370375,7.7500,NaN,Q
289,290,1,3,"Connolly, Miss. Kate",female,22.0,0,0,370373,7.7500,NaN,Q
300,301,1,3,"Kelly, Miss. Anna Katherine ""Annie Kate""",female,NaN,0,0,9234,7.7500,NaN,Q
330,331,1,3,"McCoy, Miss. Agnes",female,NaN,2,0,367226,23.2500,NaN,Q
358,359,1,3,"McGovern, Miss. Mary",female,NaN,0,0,330931,7.8792,NaN,Q
359,360,1,3,"Mockler, Miss. Helen Mary ""Ellie""",female,NaN,0,0,330980,7.8792,NaN,Q
368,369,1,3,"Jermyn, Miss. Annie",female,NaN,0,0,14313,7.7500,NaN,Q
573,574,1,3,"Kelly, Miss. Mary",female,NaN,0,0,14312,7.7500,NaN,Q
612,613,1,3,"Murphy, Miss. Margaret Jane",female,NaN,1,0,367230,15.5000,NaN,Q
653,654,1,3,"O'Leary, Miss. Hanora ""Norah""",female,NaN,0,0,330919,7.8292,NaN,Q
697,698,1,3,"Mullens, Miss. Katherine ""Katie""",female,NaN,0,0,35852,7.7333,NaN,Q
727,728,1,3,"Mannion, Miss. Margareth",female,NaN,0,0,36866,7.7375,NaN,Q

**Aggregate Functions** ~ *mean(), median(), groupby() etc.*

In [ ]:
# To handle missing values, median() is so significant
titanic_df.median(numeric_only=True)

PassengerId    446.0000
Survived         0.0000
Pclass           3.0000
Age             28.0000
SibSp            0.0000
Parch            0.0000
Fare            14.4542
dtype: float64

In [ ]:
titanic_df.mean(numeric_only=True)

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [116]:
# Find the age of the most youngest guy
titanic_df["Age"].min()

np.float64(0.42)

In [ ]:
# In which row ?
titanic_df["Age"].argmin()

np.int64(803)

In [ ]:
# Find the age of the most oldest guy
titanic_df["Age"].max()

np.float64(80.0)

In [118]:
# Print his/her full details
titanic_df.loc[titanic_df["Age"].argmax()]

PassengerId                                     631
Survived                                          1
Pclass                                            1
Name           Barkworth, Mr. Algernon Henry Wilson
Sex                                            male
Age                                            80.0
SibSp                                             0
Parch                                             0
Ticket                                        27042
Fare                                           30.0
Cabin                                           A23
Embarked                                          S
Name: 630, dtype: object

In [ ]:
titanic_df["Age"].count()
# The column "Age" has 714 non-null values

np.int64(714)

In [114]:
titanic_df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
# Too significant for Handling missing values
titanic_df["Age"].skew()

np.float64(0.38910778230082704)

In [ ]:
# By this, we can find a great hint for prediction
titanic_df[["Embarked","Fare"]].groupby("Embarked").mean()
# Who embarked from Cherbourg, they were rich

               Fare
Embarked
C         59.954144
Q         13.276030
S         27.079812

In [ ]:
titanic_df[(titanic_df["Embarked"]=="C") & (titanic_df["Pclass"]==1)] # verification

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
842,843,1,1,"Serepeca, Miss. Augusta",female,30.0,0,0,113798,31.0000,NaN,C
849,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,0,17453,89.1042,C92,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
titanic_df[["Sex", "Survived"]].groupby("Sex").mean()

        Survived
Sex
female  0.742038
male    0.188908

In [135]:
titanic_df[["Embarked", "Survived"]].groupby("Embarked").mean().sort_values(by="Survived", ascending=False)

          Survived
Embarked
C         0.553571
Q         0.389610
S         0.336957

In [ ]:
# mode -> Categorical data's most occurred value
titanic_df["Embarked"].mode()

0    S
Name: Embarked, dtype: str

**Data Cleaning**

In [ ]:
# Drop irrelevent column(s)

# titanic_df.drop(columns="Cabin") # Cabin info is not so significant to predict
titanic_df.drop(columns=["Cabin", "Ticket"]) # multiple column dropping at a time

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,7.7500,Q

In [141]:
# Handling missing data(s)
# Our age and embarking port name is significant to make prediction but it have null values
titanic_df["Age"].isnull().sum()

np.int64(177)

In [142]:
# 177 passengers age value is missing, so we will replace it with median value
titanic_df["Age"].skew()

np.float64(0.38910778230082704)

In [167]:
# if value of skew lies between -0.5 ~ 0.5, then in case of replacing mean can be 
# used instead median but median always perfect
titanic_df["Age"].fillna(titanic_df["Age"].median())
# Study about inplace and it's behavior

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [166]:
titanic_df["Age"].isnull().sum() # real object isn't updated :')

np.int64(177)

In [155]:
titanic_df["Embarked"].isnull().sum()

np.int64(2)

In [162]:
# We will fill this segment with it's mode
titanic_df["Embarked"].fillna(titanic_df["Embarked"].mode())

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: str

In [163]:
titanic_df["Embarked"].isnull().sum()

np.int64(2)

In [ ]:
# Dropping Row(s)

# Dropping the rows who's age are NaN
titanic_df.dropna(subset=["Age"])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [171]:
titanic_df.fillna({"Cabin" : "None"})

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,None,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,None,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,None,Q

In [172]:
titanic_df.fillna({"Age" : titanic_df["Age"].median()})

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [176]:
# Standardize Text
titanic_df["Name"] = titanic_df["Name"].str.upper()
display(titanic_df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"BRAUND, MR. OWEN HARRIS",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"HEIKKINEN, MISS. LAINA",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"ALLEN, MR. WILLIAM HENRY",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"MONTVILA, REV. JUOZAS",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"GRAHAM, MISS. MARGARET EDITH",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"JOHNSTON, MISS. CATHERINE HELEN ""CARRIE""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"BEHR, MR. KARL HOWELL",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"DOOLEY, MR. PATRICK",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# Fix data types
titanic_df["Survived"] = titanic_df["Survived"].astype(bool)
display(titanic_df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,False,3,"BRAUND, MR. OWEN HARRIS",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,True,1,"CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,True,3,"HEIKKINEN, MISS. LAINA",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,True,1,"FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)",female,35.0,1,0,113803,53.1000,C123,S
4,5,False,3,"ALLEN, MR. WILLIAM HENRY",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,False,2,"MONTVILA, REV. JUOZAS",male,27.0,0,0,211536,13.0000,NaN,S
887,888,True,1,"GRAHAM, MISS. MARGARET EDITH",female,19.0,0,0,112053,30.0000,B42,S
888,889,False,3,"JOHNSTON, MISS. CATHERINE HELEN ""CARRIE""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,True,1,"BEHR, MR. KARL HOWELL",male,26.0,0,0,111369,30.0000,C148,C
890,891,False,3,"DOOLEY, MR. PATRICK",male,32.0,0,0,370376,7.7500,NaN,Q

In [186]:
# Remove duplicates
legends = {
    "Name": [
        "Badhon", "Messi", "Ronaldo", "Meloni",
        "Badhon", "Messi", "Ronaldo", "Meloni",
        "Badhon", "Messi"
    ],
    "City": [
        "Jessore", "Miami", "Madrid", "Rome",
        "Dhaka", "Paris", "Turin", "Milan",
        "Khulna", "Barcelona"
    ],
    "Marks": [
        85, 95, 93, 88,
        78, 98, 90, 91,
        88, 99
    ],
    "Nickname": [
        "BD", "Leo", "CR7", "Giorgia",
        "BDX", "Mess", "R7", "GM",
        "Bad", "GOAT"
    ]
}

legend_df = pd.DataFrame(legends)
display(legend_df)

      Name       City  Marks Nickname
0   Badhon    Jessore     85       BD
1    Messi      Miami     95      Leo
2  Ronaldo     Madrid     93      CR7
3   Meloni       Rome     88  Giorgia
4   Badhon      Dhaka     78      BDX
5    Messi      Paris     98     Mess
6  Ronaldo      Turin     90       R7
7   Meloni      Milan     91       GM
8   Badhon     Khulna     88      Bad
9    Messi  Barcelona     99     GOAT

In [184]:
legend_df = legend_df.drop_duplicates(subset="Name")
display(legend_df)

      Name     City  Marks Nickname
0   Badhon  Jessore     85       BD
1    Messi    Miami     95      Leo
2  Ronaldo   Madrid     93      CR7
3   Meloni     Rome     88  Giorgia